"""
safety.py
---------
Guardrail 3 of 3 — Safety Checks

Final security layer before any query reaches the database.
Catches SQL injection, data exfiltration patterns, and
anything the validator might have missed.

Functions:
    safety_check()       → comprehensive final safety scan
    scan_for_injection() → detect SQL injection patterns
    scan_for_exfiltration() → detect data dump patterns
"""

import re
from typing import Optional

# ------------------------------------------------------------------
# Injection patterns — things that should never appear in
# a legitimate SELECT query generated by the LLM
# ------------------------------------------------------------------

INJECTION_PATTERNS = [
    # Classic SQL injection
    (r"'\s*OR\s*'",              "OR-based injection"),
    (r"'\s*AND\s*'",             "AND-based injection"),
    (r"1\s*=\s*1",               "Always-true condition"),
    (r"1\s*=\s*0",               "Always-false condition"),
    (r"'\s*;\s*--",              "Comment injection"),
    (r"UNION\s+SELECT",          "UNION-based injection"),
    (r"UNION\s+ALL\s+SELECT",    "UNION ALL injection"),

    # SQLite-specific attacks
    (r"ATTACH\s+DATABASE",       "Database attachment attack"),
    (r"LOAD_EXTENSION",          "Extension loading attack"),
    (r"sqlite_master",           "Schema enumeration"),
    (r"sqlite_sequence",         "Sequence enumeration"),

    # Blind injection indicators
    (r"WAITFOR\s+DELAY",         "Time-based blind injection"),
    (r"BENCHMARK\s*\(",          "Benchmark-based injection"),
    (r"SLEEP\s*\(",              "Sleep-based injection"),
]

# ------------------------------------------------------------------
# Exfiltration patterns — signs the query is trying to
# dump large amounts of sensitive data
# ------------------------------------------------------------------

EXFILTRATION_PATTERNS = [
    (r"SELECT\s+\*\s+FROM\s+\w+\s*;?\s*$",     "Unrestricted table dump"),
    (r"SELECT\s+\*\s+FROM\s+employees",          "Employee data dump"),
    (r"SELECT\s+.*salary.*FROM",                 "Salary data extraction"),
    (r"SELECT\s+.*password.*FROM",               "Password extraction attempt"),
    (r"SELECT\s+.*phone.*FROM\s+employees",      "Employee PII extraction"),
]


# ------------------------------------------------------------------
# Guardrail 3: safety_check()
# ------------------------------------------------------------------

def safety_check(
    sql:     str,
    user_id: str = "default_user",
) -> dict:
    """
    Final comprehensive safety scan before database execution.
    Runs injection and exfiltration checks.

    Args:
        sql:     The SQL query to scan.
        user_id: The user making the request (for logging).

    Returns:
        dict with:
        {
            "safe":    True/False,
            "checks":  {
                "injection":     {"passed": bool, "details": str},
                "exfiltration":  {"passed": bool, "details": str},
            },
            "reason":  "Safe to execute" or threat description
        }
    """
    checks = {}

    # ── Check 1: SQL injection ──────────────────────────────────
    injection_result = scan_for_injection(sql)
    checks["injection"] = injection_result
    if not injection_result["passed"]:
        _log_threat(user_id, sql, injection_result["threat"])
        return {
            "safe":   False,
            "checks": checks,
            "reason": f"Injection pattern detected: {injection_result['threat']}",
        }

    # ── Check 2: Data exfiltration ──────────────────────────────
    exfil_result = scan_for_exfiltration(sql)
    checks["exfiltration"] = exfil_result
    if not exfil_result["passed"]:
        _log_threat(user_id, sql, exfil_result["threat"])
        return {
            "safe":   False,
            "checks": checks,
            "reason": f"Exfiltration pattern detected: {exfil_result['threat']}",
        }

    return {
        "safe":   True,
        "checks": checks,
        "reason": "Safe to execute",
    }


# ------------------------------------------------------------------
# Guardrail 3A: scan_for_injection()
# ------------------------------------------------------------------

def scan_for_injection(sql: str) -> dict:
    """
    Scans SQL for injection attack patterns.

    Args:
        sql: The SQL query to scan.

    Returns:
        dict with passed status, threat name if found.
    """
    sql_upper = sql.upper()

    for pattern, threat_name in INJECTION_PATTERNS:
        if re.search(pattern, sql_upper, re.IGNORECASE):
            return {
                "passed": False,
                "threat": threat_name,
                "details": f"Blocked: {threat_name}",
            }

    return {
        "passed":  True,
        "threat":  None,
        "details": "No injection patterns detected",
    }


# ------------------------------------------------------------------
# Guardrail 3B: scan_for_exfiltration()
# ------------------------------------------------------------------

def scan_for_exfiltration(sql: str) -> dict:
    """
    Scans SQL for data exfiltration patterns.

    Args:
        sql: The SQL query to scan.

    Returns:
        dict with passed status, threat name if found.
    """
    for pattern, threat_name in EXFILTRATION_PATTERNS:
        if re.search(pattern, sql, re.IGNORECASE):
            return {
                "passed": False,
                "threat": threat_name,
                "details": f"Blocked: {threat_name}",
            }

    return {
        "passed":  True,
        "threat":  None,
        "details": "No exfiltration patterns detected",
    }


# ------------------------------------------------------------------
# Helper: threat logging
# ------------------------------------------------------------------

_threat_log = []   # In production: write to security log / SIEM

def _log_threat(user_id: str, sql: str, threat: str) -> None:
    """Logs a detected threat for security monitoring."""
    import time
    _threat_log.append({
        "timestamp": time.time(),
        "user_id":   user_id,
        "threat":    threat,
        "sql":       sql[:200],   # Truncate for log safety
    })


def get_threat_log() -> list:
    """Returns the threat log for security monitoring."""
    return _threat_log.copy()


# ------------------------------------------------------------------
# Quick self-test
# ------------------------------------------------------------------

if __name__ == "__main__":

    test_cases = [
        # (description, sql, expected_safe)
        (
            "Clean SELECT query",
            "SELECT product_name, unit_price FROM products ORDER BY unit_price DESC LIMIT 10",
            True,
        ),
        (
            "Clean JOIN query",
            "SELECT c.company_name, COUNT(o.order_id) as order_count FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id",
            True,
        ),
        (
            "UNION injection attempt",
            "SELECT product_name FROM products UNION SELECT password FROM users",
            False,
        ),
        (
            "Always-true injection",
            "SELECT * FROM orders WHERE 1=1",
            False,
        ),
        (
            "Schema enumeration",
            "SELECT * FROM sqlite_master",
            False,
        ),
        (
            "Sleep-based blind injection",
            "SELECT * FROM orders WHERE SLEEP(5)",
            False,
        ),
        (
            "Salary extraction",
            "SELECT first_name, salary FROM employees",
            False,
        ),
    ]

    print("=" * 60)
    print("SAFETY TESTS")
    print("=" * 60)

    all_passed = True
    for desc, sql, expected_safe in test_cases:
        result = safety_check(sql, user_id="test_user")
        status = "✅" if result["safe"] == expected_safe else "❌"
        if result["safe"] != expected_safe:
            all_passed = False

        print(f"\n{status} {desc}")
        print(f"   Safe     : {result['safe']} (expected: {expected_safe})")
        if not result["safe"]:
            print(f"   Reason   : {result['reason']}")

    print("\n── Threat Log ──")
    for threat in get_threat_log():
        print(f"   🚨 {threat['threat']} by {threat['user_id']}")

    print("\n" + "=" * 60)
    print(f"{'✅ All tests passed' if all_passed else '❌ Some tests failed'}")
    print("=" * 60)